db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
music_directory    "~/music/"
playlist_directory "~/.config/mpd/playlists"
state_file         "~/.local/state/mpd/state"

audio_output {
    type        "pipewire"
    name        "Pipewire Sound Server"
}

